// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx1itI_a8mtsUrSYUfBSwXlnuFHpxbZ-Q',
    appId: '1:1087553333821:web:c388cc82cb6dc3d193d854',
    messagingSenderId: '1087553333821',
    projectId: 'testflutter-326a2',
    authDomain: 'testflutter-326a2.firebaseapp.com',
    storageBucket: 'testflutter-326a2.appspot.com',
    measurementId: 'G-0F87TFS686',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJshzwVtj9pRCB-K10xWDr0UVoMOj_IE',
    appId: '1:1087553333821:android:74ca4c1e862c741c93d854',
    messagingSenderId: '1087553333821',
    projectId: 'testflutter-326a2',
    storageBucket: 'testflutter-326a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2rTnqPkFXYHZwgyidPLPVhw9nk4BVss',
    appId: '1:1087553333821:ios:11ca32339180e4b893d854',
    messagingSenderId: '1087553333821',
    projectId: 'testflutter-326a2',
    storageBucket: 'testflutter-326a2.appspot.com',
    iosBundleId: 'com.example.tweetFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN2rTnqPkFXYHZwgyidPLPVhw9nk4BVss',
    appId: '1:1087553333821:ios:e04b4121faf4c07793d854',
    messagingSenderId: '1087553333821',
    projectId: 'testflutter-326a2',
    storageBucket: 'testflutter-326a2.appspot.com',
    iosBundleId: 'com.example.tweetFeed.RunnerTests',
  );
}
